language: node_js
node_js:
 - "5.9.0"
 - "4.4.0"
before_install:
  - "mv config.json.example config.json"
script:
  - "npm test"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cb239e5480024fa63aad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
